/**
 * extract-schema.js
 *
 * Reads the WebStudio model JSON schema and produces
 * webstudio-builder/src/generated/schema-meta.ts with:
 *   - WidgetType union
 *   - ActionType union
 *   - SendTopic union
 *   - AggregateType union
 *   - LifecycleHook union
 *   - TabActivation union
 *   - LoadCompilationSubType union
 *
 * Usage: node webstudio-builder/scripts/extract-schema.js [path-to-schema.json]
 */

const fs = require("fs");
const path = require("path");

const defaultSchemaPath = path.resolve(
    __dirname,
    "../../13043-1.100.8.25461/webstudio/drawio/custom-plugins/webstudio-model-schema.json",
);

const schemaPath = process.argv[2] || defaultSchemaPath;

if (!fs.existsSync(schemaPath)) {
    console.error(`Schema not found: ${schemaPath}`);
    process.exit(1);
}

const schema = JSON.parse(fs.readFileSync(schemaPath, "utf8"));
const defs = schema.definitions || {};

// ── Helpers ────────────────────────────────────────────────────────────────

function constFromType(def) {
    const t = def && def.properties && def.properties.type;
    if (!t) return null;
    if (t.const) return t.const;
    if (t.enum && t.enum.length === 1) return t.enum[0];
    return null;
}

function enumValues(name) {
    const d = defs[name];
    return d && Array.isArray(d.enum) ? d.enum : [];
}

function toUnion(values) {
    return values.map(v => `    | "${v}"`).join("\n");
}

// ── Extract ────────────────────────────────────────────────────────────────

// Widget types
const widgetTypes = Object.entries(defs)
    .filter(([n]) => /WidgetModel$/.test(n) && n !== "IWidgetModel" && n !== "ITreeBaseWidgetModel")
    .map(([, s]) => constFromType(s))
    .filter(Boolean)
    .sort();

const uniqueWidgetTypes = [...new Set(widgetTypes)];

// Action types
const actionTypes = Object.entries(defs)
    .filter(([n]) => /ActionModel$/.test(n))
    .map(([, s]) => constFromType(s))
    .filter(Boolean)
    .sort();

const uniqueActionTypes = [...new Set(actionTypes)];

// Send topics
const sendModel = defs.ISendActionModel;
const topicDeps = sendModel
    && sendModel.properties
    && sendModel.properties.message
    && sendModel.properties.message.dependencies
    && sendModel.properties.message.dependencies.topic;

const topics = [];
if (topicDeps && topicDeps.allOf) {
    for (const entry of topicDeps.allOf) {
        if (entry.if && entry.if.properties && entry.if.properties.topic && entry.if.properties.topic.const) {
            topics.push(entry.if.properties.topic.const);
        }
    }
}
topics.sort();

// Enums
const aggregateValues = enumValues("Aggregate");
const activateTabValues = enumValues("ActivateTab");
const loadCompSubTypes = enumValues("LoadCompilationActionSubType");
const loadCompHistoryTypes = enumValues("LoadCompilationHistoryType");
const envQueryValues = enumValues("EnvironmentQuery");
const uiWidgetTypes = enumValues("UIWidgetType");
const timeZoneValues = enumValues("TimeZone");
const boundsValues = enumValues("BoundsMode");

// Lifecycle hooks (union of all declared action hook names)
const lifecycleHooks = new Set();
for (const [n, s] of Object.entries(defs)) {
    if (!/WidgetModel$/.test(n)) continue;
    if (s.properties && s.properties.actions && s.properties.actions.properties) {
        for (const hook of Object.keys(s.properties.actions.properties)) {
            lifecycleHooks.add(hook);
        }
    }
}
const sortedHooks = [...lifecycleHooks].sort();

// ── Generate ───────────────────────────────────────────────────────────────

const output = `// AUTO-GENERATED by scripts/extract-schema.js — do not edit manually.
// Source: webstudio-model-schema.json

// ─── Widget types ─────────────────────────────────────────────────────────────

export type WidgetType =
${toUnion(uniqueWidgetTypes)};

// ─── Action types ─────────────────────────────────────────────────────────────

export type ActionType =
${toUnion(uniqueActionTypes)};

// ─── Send topics ──────────────────────────────────────────────────────────────

export type SendTopic =
${toUnion(topics)};

// ─── Lifecycle & widget action hooks ──────────────────────────────────────────

export type ActionHook =
${toUnion(sortedHooks)};

// ─── Aggregate types ──────────────────────────────────────────────────────────

export type AggregateType =
${toUnion(aggregateValues)};

// ─── Tab activation modes ─────────────────────────────────────────────────────

export type TabActivation =
${toUnion(activateTabValues)};

// ─── Load-compilation sub-types ───────────────────────────────────────────────

export type LoadCompilationSubType =
${toUnion(loadCompSubTypes)};

// ─── Load-compilation history types ───────────────────────────────────────────

export type LoadCompilationHistoryType =
${toUnion(loadCompHistoryTypes)};

// ─── Environment queries ──────────────────────────────────────────────────────

export type EnvironmentQueryType =
${toUnion(envQueryValues)};

// ─── Advanced form UI widget types ────────────────────────────────────────────

export type UIWidgetType =
${toUnion(uiWidgetTypes)};

// ─── Time zone ────────────────────────────────────────────────────────────────

export type TimeZoneType =
${toUnion(timeZoneValues)};

// ─── Bounds mode (raw historical data) ────────────────────────────────────────

export type BoundsMode = ${boundsValues.join(" | ")};

// ─── Constant arrays (for runtime iteration) ─────────────────────────────────

export const WIDGET_TYPES: WidgetType[] = [
${uniqueWidgetTypes.map(v => `    "${v}",`).join("\n")}
];

export const ACTION_TYPES: ActionType[] = [
${uniqueActionTypes.map(v => `    "${v}",`).join("\n")}
];

export const SEND_TOPICS: SendTopic[] = [
${topics.map(v => `    "${v}",`).join("\n")}
];

export const ACTION_HOOKS: ActionHook[] = [
${sortedHooks.map(v => `    "${v}",`).join("\n")}
];

export const AGGREGATE_TYPES: AggregateType[] = [
${aggregateValues.map(v => `    "${v}",`).join("\n")}
];
`;

// ── Write ──────────────────────────────────────────────────────────────────

const outDir = path.resolve(__dirname, "../src/generated");
if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
}

const outPath = path.join(outDir, "schema-meta.ts");
fs.writeFileSync(outPath, output, "utf8");
console.log(`✓ Generated ${outPath}`);
console.log(`  ${uniqueWidgetTypes.length} widget types, ${uniqueActionTypes.length} action types, ${topics.length} send topics, ${sortedHooks.length} hooks`);
