/**
 * WorkspaceDocumentExample
 *
 * USE CASE
 * --------
 * A deployment orchestrator script lives at:
 *   /System/Core/Automation/Orchestrator
 *
 * When it runs it needs to:
 *   1. Know its own location in the model (Workspace) so it can compute
 *      sibling paths without hardcoding them.
 *
 *   2. Build a Lua processing script dynamically (Document) that is
 *      parameterised with the orchestrator's path — so the generated
 *      script can call back to the orchestrator for coordination.
 *
 *   3. Write the generated script to disk for audit purposes, then push
 *      it into a sibling Script Object via syslib.
 *
 * This pattern is typical in self-deploying inmation solutions where the
 * same TypeScript bundle provisions its own sibling objects.
 *
 * Demonstrates: Workspace.path/name/parentPath, Document (append/insert/
 * replace/findLine/remove/toString), and the interplay between the two.
 */
import { Workspace } from "../std/Workspace";
import { Document } from "../std/Document";
import { File } from "../std/File";

export function main(): void {
    // ─────────────────────────────────────────────────────────────────────
    // 1. Workspace — figure out where we are
    //    Falls back to a known path when running outside a Script Object
    //    (e.g. via froge run, where Host.workspace.info() returns nil).
    // ─────────────────────────────────────────────────────────────────────
    let selfPath   = "/System/Core/Automation/Orchestrator";
    let selfName   = "Orchestrator";
    let parentPath = "/System/Core/Automation";
    try {
        selfPath   = Workspace.path();
        selfName   = Workspace.scriptName();
        parentPath = Workspace.parentPath();
    } catch (e) {
        console.log(`[1] Workspace not available (running outside Script Object) — using fallback paths`);
    }

    console.log(`[1] Workspace path  : ${selfPath}`);
    console.log(`[1] Workspace name  : ${selfName}`);
    console.log(`[1] Parent path     : ${parentPath}`);

    // Compute sibling paths relative to self — no hardcoded strings
    const processorPath   = `${parentPath}/Processor`;
    const configPath      = `${parentPath}/Config`;
    const logArchivePath  = `${parentPath}/LogArchive`;

    console.log(`[1] Sibling paths   : ${processorPath}, ${configPath}, ${logArchivePath}`);

    // ─────────────────────────────────────────────────────────────────────
    // 2. Document — build a parameterised Lua processing script
    // ─────────────────────────────────────────────────────────────────────
    const script = new Document();

    // Header block
    script
        .append(`-- Auto-generated by ${selfName}`)
        .append(`-- Orchestrator path: ${selfPath}`)
        .append(`-- Do not edit manually`)
        .append("")
        .append(`local orchestratorPath = "${selfPath}"`)
        .append(`local configPath       = "${configPath}"`)
        .append(`local logArchivePath   = "${logArchivePath}"`)
        .append("")
        .append(`-- Read configuration from the Config object`)
        .append(`local cfgJson = syslib.getvalue(configPath .. ".AdvancedLuaScript")`)
        .append(`local cfg = (cfgJson and require("dkjson").decode(cfgJson)) or {}`)
        .append("")
        .append(`-- Processing function called on each trigger`)
        .append(`local function process(item)`)
        .append(`    local threshold = cfg.threshold or 100`)
        .append(`    if item.value > threshold then`)
        .append(`        syslib.log(3, "Threshold exceeded: " .. tostring(item.value))`)
        .append(`    end`)
        .append(`    return item`)
        .append(`end`)
        .append("")
        .append(`return process`);

    console.log(`[2] Script built — ${String(script.count)} lines`);

    // ─────────────────────────────────────────────────────────────────────
    // 3. Document editing — inject a version header at line 1 after review
    // ─────────────────────────────────────────────────────────────────────
    script.insert(1, `-- Version: 1.0.0  Generated: (see audit log)`);
    console.log(`[3] Version header injected — now ${String(script.count)} lines`);

    // ─────────────────────────────────────────────────────────────────────
    // 4. Document search — find the threshold line and bump it to 150
    // ─────────────────────────────────────────────────────────────────────
    const thresholdLine = script.findLine(l => l.indexOf("threshold or") !== -1);
    if (thresholdLine > 0) {
        script.replace(thresholdLine, `    local threshold = cfg.threshold or 150`);
        console.log(`[4] Threshold default updated at line ${String(thresholdLine)}`);
    }

    // ─────────────────────────────────────────────────────────────────────
    // 5. Document — strip the blank separator lines for a compact version
    // ─────────────────────────────────────────────────────────────────────
    const compact = Document.fromLines(
        script.filter(l => l.length > 0)
    );
    console.log(`[5] Compact script — ${String(compact.count)} lines (${String(script.count - compact.count)} blank lines removed)`);

    // ─────────────────────────────────────────────────────────────────────
    // 6. Write both versions to disk for audit
    // ─────────────────────────────────────────────────────────────────────
    const baseDir = File.cwd();
    File.write(`${baseDir}/generated_processor.lua`, script.toString());
    File.write(`${baseDir}/generated_processor_compact.lua`, compact.toString());
    console.log(`[6] Scripts written to disk`);

    // ─────────────────────────────────────────────────────────────────────
    // 7. Push the full script into the sibling Processor Script Object
    //    (create parent folder and object if they don't exist)
    // ─────────────────────────────────────────────────────────────────────
    // Ensure the parent folder exists (needed when using fallback paths)
    if (!syslib.getobject(parentPath)) {
        let lastSlash = 0;
        for (let i = parentPath.length - 1; i >= 0; i--) {
            if (parentPath.substring(i, i + 1) === "/") { lastSlash = i; break; }
        }
        const parentName = parentPath.substring(lastSlash + 1);
        syslib.mass([{
            class: syslib.model.classes.GenFolder,
            operation: syslib.model.codes.MassOp.UPSERT,
            path: parentPath,
            ObjectName: parentName,
        }]);
    }
    if (!syslib.getobject(processorPath)) {
        syslib.mass([{
            class: syslib.model.classes.ActionItem,
            operation: syslib.model.codes.MassOp.UPSERT,
            path: processorPath,
            ObjectName: "Processor",
            AdvancedLuaScript: script.toString(),
        }]);
        console.log(`[7] Created Processor Script Object at ${processorPath}`);
    } else {
        syslib.setvalue(`${processorPath}.AdvancedLuaScript`, script.toString());
        console.log(`[7] Updated script on existing Processor at ${processorPath}`);
    }

    // ─────────────────────────────────────────────────────────────────────
    // 8. Verify round-trip — read back what was written
    // ─────────────────────────────────────────────────────────────────────
    const readBack = syslib.getvalue(`${processorPath}.AdvancedLuaScript`) as string | undefined;
    if (readBack) {
        const readDoc = new Document(readBack);
        const versionLine = readDoc.findLine(l => l.indexOf("Version:") !== -1);
        console.log(`[8] Round-trip OK — ${String(readDoc.count)} lines, version header at line ${String(versionLine)}`);
    } else {
        console.log(`[8] Could not read back script (object may not exist in this environment)`);
    }

    console.log(`\n[Done] Orchestrator self-deployment complete`);
}
